// api/github/export.js
import { admin } from "../../fire_prompt_admin.js";

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ message: 'Method Not Allowed' });

  const { projectId, projectName, files, userGitHubToken } = req.body;
  const authHeader = req.headers.authorization;

  if (!authHeader || !userGitHubToken) {
    return res.status(401).json({ message: 'Missing Authorization or GitHub Token' });
  }

  try {
    const idToken = authHeader.split('Bearer ')[1];
    await admin.auth().verifyIdToken(idToken);

    const headers = {
      'Authorization': `token ${userGitHubToken}`,
      'Accept': 'application/vnd.github.v3+json',
      'User-Agent': 'AmmoueAI-App',
      'Content-Type': 'application/json'
    };

    const userRes = await fetch('https://api.github.com/user', { headers });
    if (!userRes.ok) throw new Error("Invalid GitHub Token provided by user.");
    const userData = await userRes.json();
    const username = userData.login;

    const repoName = projectName.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
    
    const createRepoRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers,
      body: JSON.stringify({
        name: repoName,
        description: `Generated by AmmoueAI`,
        auto_init: true
      })
    });

    if (createRepoRes.status !== 201 && createRepoRes.status !== 422) {
       const err = await createRepoRes.text();
       throw new Error(`Failed to create repo: ${err}`);
    }

    await new Promise(r => setTimeout(r, 2000));

    const refRes = await fetch(`https://api.github.com/repos/${username}/${repoName}/git/refs/heads/main`, { headers });
    const refData = await refRes.json();
    const latestCommitSha = refData.object.sha;

    const treeItems = Object.entries(files).map(([path, content]) => ({
      path,
      mode: '100644',
      type: 'blob',
      content
    }));

    const treeRes = await fetch(`https://api.github.com/repos/${username}/${repoName}/git/trees`, {
      method: 'POST',
      headers,
      body: JSON.stringify({ tree: treeItems, base_tree: latestCommitSha })
    });
    const treeData = await treeRes.json();

    const commitRes = await fetch(`https://api.github.com/repos/${username}/${repoName}/git/commits`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        message: `AmmoueAI Export: ${projectName}`,
        tree: treeData.sha,
        parents: [latestCommitSha]
      })
    });
    const commitData = await commitRes.json();

    await fetch(`https://api.github.com/repos/${username}/${repoName}/git/refs/heads/main`, {
      method: 'PATCH',
      headers,
      body: JSON.stringify({ sha: commitData.sha })
    });

    res.status(200).json({ 
      success: true, 
      repoUrl: `https://github.com/${username}/${repoName}` 
    });

  } catch (error) {
    res.status(500).json({ message: error.message });
  }
}
